package modelo;
// Generated 2 mar 2023 0:00:13 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccMovement generated by hbm2java
 */
@Entity
@Table(name = "ACC_MOVEMENT", catalog = "empresa")
public class AccMovement implements java.io.Serializable {

	private Integer accountMovId;
	private Account account;
	private int accountOriginId;
	private BigDecimal amount;
	private Date datetime;
	private Date fecha;

	public AccMovement() {
	}

	public AccMovement(Account account, int accountOriginId, BigDecimal amount, Date datetime) {
		this.account = account;
		this.accountOriginId = accountOriginId;
		this.amount = amount;
		this.datetime = datetime;
	}

	public AccMovement(Account account, int accountOriginId, BigDecimal amount, Date datetime, Date fecha) {
		this.account = account;
		this.accountOriginId = accountOriginId;
		this.amount = amount;
		this.datetime = datetime;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCOUNT_MOV_ID", unique = true, nullable = false)
	public Integer getAccountMovId() {
		return this.accountMovId;
	}

	public void setAccountMovId(Integer accountMovId) {
		this.accountMovId = accountMovId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_DEST_ID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "ACCOUNT_ORIGIN_ID", nullable = false)
	public int getAccountOriginId() {
		return this.accountOriginId;
	}

	public void setAccountOriginId(int accountOriginId) {
		this.accountOriginId = accountOriginId;
	}

	@Column(name = "AMOUNT", nullable = false, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME", nullable = false, length = 23)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
