package modelo;
// Generated 2 mar 2023 0:00:13 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT", catalog = "empresa")
public class Account implements java.io.Serializable {

	private Integer accountno;
	private Emp emp;
	private BigDecimal amount;
	private Set<AccMovement> accMovements = new HashSet<AccMovement>(0);

	public Account() {
	}

	public Account(Emp emp, BigDecimal amount) {
		this.emp = emp;
		this.amount = amount;
	}

	public Account(Emp emp, BigDecimal amount, Set<AccMovement> accMovements) {
		this.emp = emp;
		this.amount = amount;
		this.accMovements = accMovements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCOUNTNO", unique = true, nullable = false)
	public Integer getAccountno() {
		return this.accountno;
	}

	public void setAccountno(Integer accountno) {
		this.accountno = accountno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPNO", nullable = false)
	public Emp getEmp() {
		return this.emp;
	}

	public void setEmp(Emp emp) {
		this.emp = emp;
	}

	@Column(name = "AMOUNT", nullable = false, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<AccMovement> getAccMovements() {
		return this.accMovements;
	}

	public void setAccMovements(Set<AccMovement> accMovements) {
		this.accMovements = accMovements;
	}

}
